### ISSUE TITLE
eclipse以外での実行

### ISSUE THREAD

**Issue by 3tty0n** [rec0/TetriVSproto#1]
README.mdに

> 使い方については、右上にあるDL ZIP的なのを押してダウンロードした後に eclipseにインポートしてあげれば実行可能なはず…実行できない時はどんな状況でかも含めて 教えてもらえるとありがたい

とありますが、ターミナルで実行する場合はどうすればいいですか？

**Comment by rec0** [comment]
質問ありがとうございます。
ターミナルで実行するにはどうすれば良いかという質問ですね。
すみませんが自分の環境がeclipseで実行していることもあり、ターミナルでコンパイルする方法がわからないですorz　　
最終的にGUIScrean.javaをコンパイルしたものを動かすことができれば動くかとは思います。
テスト週間が明けてからまた検討考察して返答しようと思いますので、今のところはこの程度の回答でお願いします

**Comment by rec0** [comment]
お待たせいたしました。
ターミナルでコンパイル及び実行を行うということでよろしかったでしょうか？
コンパイルの実行は、クラスパスをパッケージの上部であるsrcに通すことで可能になります。
例えばこのファイルをダウンロードしたままであれば、カレントリをGUIScrean.javaがあるところまで移動してもらって「javac -cp "../../../../src" GUIScrean.java」と実行することでコンパイル可能かと思います
次に、実行ですが、今度はカレントディレクトリをsrcに移ってもらって、「java jp.ac.tetrivs.GUIScrean」と入力すると実行ができるかと思います。
これで解答になっているかわかりませんが、不明点等ありましたらまた追加で質問を宜しくお願いします。
